name: "Restore SQLite"

author: "ryohidaka"

description: "GitHub Actions to restore SQLite DB from dump file."

branding:
  color: green
  icon: send

inputs:
  version:
    description: "SQLite version to install (optional)"
    required: false
    default: "latest"

  db:
    description: "The output SQLite database file name."
    required: true

  dump-file:
    description: "The name of the dump file to use."
    required: true

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Setup SQLite environment
      uses: ryohidaka/action-setup-sqlite@v1.2.0
      with:
        version: ${{ inputs.version }}

    - name: Restore DB from dump file
      run: |
        $GITHUB_ACTION_PATH/scripts/restore.sh \
          ${{ inputs.db }} \
          ${{ inputs.dump-file }}
      shell: bash
