name: "Rebuild SQLite"

author: "ryohidaka"

description: "GitHub Actions to rebuild SQLite DB from dump file."

branding:
  color: green
  icon: send

inputs:

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash
